export const TODO_LOADING = "TODO_LOADING";
export const TODO_DONE_LOADING = "TODO_DONE_LOADING";
export const TODO_ERROR_LOADING = "TODO_ERROR_LOADING";
export const TODOS = "TODOS";

export const CREATE_LOADING = 'CREATE_LOADING';
export const CREATE_DONE_LOADING = 'CREATE_DONE_LOADING';
export const CREATE_ERROR_LOADING = 'CRATE_ERROR_LOADING';
export const CREATE_TODO = 'CREATE_TODO';

export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';